# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
 input:           GFM
 auto_ids:        true
 hard_wrap:       false
 syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            ferrell.io
description:      'Adventures in code, photography and life with Nate and Lauren Ferrell.'
url:              http://ferrell.io
baseurl:          /

author:
  name:           'Nate Ferrell'
  url:            https://github.com/scrthq

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/scrthq
