# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ferrell.io
tagline:          'Adventures in the future'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://ferrell.io
baseurl:          /

author:
  name:           'Nate Ferrell'
  url:            https://twitter.com/scrthq

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/scrthq
